### ISSUE TITLE
Separation of English and French Data

### ISSUE THREAD

**Issue by stef52** [CQEN-QDCE/Candy#3]
Noticed that in [Architecture-Issuer.puml](https://github.com/CQEN-QDCE/Candy/blob/main/doc/architecture/Architecture-Issuer.puml) that the data for English and French are separated. Wouldn't they share the same data source since they both follow the same schema?

**Comment by flihp27** [comment]
Cette demande est considéré désuette. La problématique de la langue sera résolu par l'implémentation OCDA (Overlays Data Capture Architecture).
